name = "whimsical-clone"
account_id = ""
main = "src/index.ts"
compatibility_date = "2024-01-01"

[env.development]
route = "http://localhost:8787"

[env.production]
route = ""

[build]
command = "npm run build"
cwd = "./"

[[env.production.routes]]
pattern = "example.com/*"
zone_name = "example.com"
